# Disable sudo to speed up the build
sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=airflowscan/
after_success:
  - codecov